<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "t3booking"
 *
 * Auto generated by Extension Builder 2014-08-26
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Buchung',
	'description' => 'Booking and Reservation System',
	'category' => 'plugin',
	'author' => 'Ralf Schneider',
	'author_email' => 'ralf@hr-interactive.com',
	'state' => 'beta',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '0.4.0',
	'constraints' => array(
		'depends' => array(
			'typo3' => '6.1',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);